### PR TITLE
Upgraded phpunit to allow 5.7 and 6.0

### PR DESCRIPTION
**Pull request by cmodijk**

### CODE REVIEW

**Comment by ruudk** [comment]
Any news in this 🙏  :D

**Comment by cmodijk** [comment]
I'm not sure how to fix this failing test. It's true that the method `isOpen` does not exists on the `ObjectManager` but the problem is that i want to know that we never use it.

**Comment by ruudk** [comment]
If you really want to do it you can mock `__call`, would that work?

**Comment by cmodijk** [comment]
Just tried this still the same;
```
Trying to configure method "__call" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

**Comment by cmodijk** [comment]
We can fix the `isOpen` call like this
https://github.com/LongRunning/LongRunning/pull/26/files#diff-0014f80d3ada364ca4247fa05a63744b

**Comment by ruudk** [comment]
Will be handled in https://github.com/LongRunning/LongRunning/pull/30

**Pull request closed without merging**
