### PR TITLE
Added cleaner for monolog fixes #2

### LINKED ISSUE #2: Reset monolog
We use the fingers_crossed logger and when we nou get an error in one command al logs and commands after that one is writing to disk. The `FingersCrossedHandler` has an reset and clear method maybe we could use this to reset it? 

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FingersCrossedHandler.php

### PR DESCRIPTION
**Pull request by cmodijk**
I implemented the idea from @matthiasnoback which uses compiler passes to inject the right services to be cleared bases on the class name. I'm not sure if the `PassConfig::TYPE_OPTIMIZE` is the right way to go but if I don't do this i'm getting the parameter versions of the classes like `%this.is.my.class%` instead of the real class. 

@matthiasnoback There is no test suit for LongRunning at the moment right?

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks, I will get back to you soon!

**Comment by matthiasnoback** [comment]
Sorry about the delay. Great work. It would be slightly better if you'd use the regular `PassConfig` type and resolve the parameters yourself. You can always do so by calling `$container->getParameterBag()->resolveValue(...)`.

**Comment by cmodijk** [comment]
@matthiasnoback Tnx for the feedback I just updated my pull request!

**Comment by matthiasnoback** [comment]
Okay,  thanks. I'll merge it soon.
Op 10 apr. 2015 17:49 schreef "Cliff Odijk" notifications@github.com:

**Comment by matthiasnoback** [comment]
Thanks man!

**Pull request merged**
