### PR TITLE
Adding test suit

### PR DESCRIPTION
**Pull request by cmodijk**
I'm still working on this branch but i'm already creating the pull to let you know i'm working on it. I would also love to hear any feedback.

One side note i changed the `ResetClosedEntityManagers` from an exception to a continue because it is possible to have DoctrineORM and Doctrine Document mapper at te same time. I don't know it they would come from the same registry but the `ManagerRegistry` say's it's possible to get a `ObjectManager`. 

I also fixed a bug that is related to my other pull request #6

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Oh, that's great news! Nice work. After this is finished, I think the package deserves to be split into smaller ones using the Gitsplit tool.

**Comment by matthiasnoback** [comment]
By the way, that would require some work to define `composer.json` files for the sub-packages as well.

**Comment by cmodijk** [comment]
@matthiasnoback Could you help me with the functional test part. I'm have tried to add the setup for functional testing the bundle but i'm stuck with a dependency hell. I based the test on the test suit in [`RabbitMQBundleBridge`](https://github.com/SimpleBus/RabbitMQBundleBridge/tree/master/tests/Functional). 

First doctrine seems to need Twig

```
PHP Fatal error:  Class 'Twig_Extension' not found in ~/LongRunning/vendor/doctrine/doctrine-bundle/Twig/DoctrineExtension.php on line 24
```

After installing twig it seems to need the form component 

```
PHP Fatal error:  Interface 'Symfony\Component\Form\FormTypeGuesserInterface' not found in ~/LongRunning/vendor/symfony/doctrine-bridge/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php on line 25
```

After that i need to install the validator component

```
PHP Fatal error:  Class 'Symfony\Component\Validator\ConstraintValidator' not found in ~/LongRunning/vendor/symfony/doctrine-bridge/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php on line 26
```

I feels strange that i need al these dependencies and i don't know how to solve this differently. I have pushed the failing functional tests as an example.

**Comment by cmodijk** [comment]
I just added a new commit with the unit tests working. If the functional tests cache is empty the test coverage is 100% i'm not sure if i should write more tests. 

Other question do you want me to rebase my test pull request to 1 commit or keep the separate commits?

**Comment by cmodijk** [comment]
Ping @matthiasnoback When do you think you have some time to review my pull request?

**Comment by matthiasnoback** [comment]
Hey man, sorry about that! Great work, last time I looked it seemed very
good to me :) I'll merge it tomorrow.

On Fri, Jun 5, 2015 at 9:58 PM, Cliff Odijk notifications@github.com
wrote:

> Ping @matthiasnoback https://github.com/matthiasnoback When do you
> think you have some time to review my pull request?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LongRunning/LongRunning/pull/9#issuecomment-109421364
> .

## 

_Noback's Office_
http://nobacksoffice.nl
+31(0)614995363

**Comment by matthiasnoback** [comment]
Hi there! Again, great work :)

I looked at your dependency problems. Some suggestions:
- You can disable forms in config.yml, see http://symfony.com/doc/current/reference/configuration/framework.html#enabled This should help fix some of the issues I think.
- The problem with Twig etc. is caused by `is_a()` on line 18 in `MonologCleanersPass`\- for some services it triggers the autoloader for a class that doesn't exist. The compiler pass itself should thus be less obtrusive. I'm not sure about the actual solution, but maybe we should not use `is_a` but use reflection instead.

The first problem is only related to the functional test itself, but the second is more important: it exposes an actual bug. By the way, this shows us the value of such a functional test, right? :) Do you have time to look at this?

**Comment by cmodijk** [comment]
Hi @matthiasnoback Tnx for the feedback. I wil look into this tonight or tomorrow.

**Comment by cmodijk** [comment]
Actually all the problems come from the `is_a` because it loops over all the services in the container an it try's to autoload everything. I have changed the `MonologCleanersPass` to detect if the `$serviceId` starts with `monolog.handler.` Because thats what the  [`MonologExtension`](https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/MonologExtension.php#L624) automatically registers as the names for the handlers. I have also added new functional tests to test the working of the monolog handlers and test the new id detection also works as expected.

**Comment by cmodijk** [comment]
Coool tnx @matthiasnoback! When do you think we could tag a stable version?

**Comment by matthiasnoback** [comment]
That's fantastic. Again: great work! And a lot of work as well. This is a very good baseline situation for any further development work. 

I realize now that before we can start splitting this one big package into several smaller ones we should reorganize the tests as well, since the subtree split should be done per directory, so all the tests for a plugin etc. should be in that directory as well. So whenever I'm going to split, I'll move everything around a bit until it fits with the tool (http://gitsplit.com/login/).

**Comment by matthiasnoback** [comment]
Ah, well, for the stable version we should wait until the big split. I should plan a couple of hours for that. It would be really useful after all. I'm not sure if it makes sense to tag a stable version before this has happened.

**Comment by cmodijk** [comment]
Hmm no that's right is there anything i can do to reorganize things and prepare for the split? PS: I'm trying to login into the gitsplit with github but i'm getting an `500 Internal Server Error`.

**Comment by matthiasnoback** [comment]
Hmm, maybe it's not so stable at the moment then. See for more information the issue I just created: https://github.com/LongRunning/LongRunning/issues/10

**Pull request merged**
