### PR TITLE
Support Symfony 3.0

### PR DESCRIPTION
**Pull request by ruudk**
Fixed: The reserved indicator "@" cannot start a plain scalar

### CODE REVIEW

**Comment by ruudk** [comment]
This one fails because of this PR https://github.com/SimpleBus/AsynchronousBundle/pull/4

**Comment by matthiasnoback** [comment]
Currently it fails because RabbitMQBundleBridge isn't Symfony 3.0 compatible yet.

**Comment by ruudk** [comment]
Working on a pull over there too https://github.com/videlalvaro/RabbitMqBundle/pull/313#partial-pull-merging

**Comment by ruudk** [comment]
Pull added https://github.com/SimpleBus/JMSSerializerBundleBridge/pull/5

**Comment by ruudk** [comment]
Can you retry this test?

**Comment by matthiasnoback** [comment]
Done and tagged. Thanks again!

**Pull request merged**
