### PR TITLE
Sentry Plugin

### PR DESCRIPTION
**Pull request by adri**
When running queues with Bernard, error messages tracked via Sentry were not sent.

Our Sentry configuration is set to send errors `async` when the script stops.
Because the script doesn't stop, errors were not sent/cleared.

Solution: A LongRunning plugin that clears the Sentry error queue after every job/failure.

### CODE REVIEW

**Comment by adri** [comment]
Will fix the coverage issues

**Comment by cmodijk** [comment]
@adri Thanks i just merged this

**Comment by adri** [comment]
Awesome, thanks!

**Comment by adri** [comment]
Would you mind tagging a new release? :)  @cmodijk

**Comment by cmodijk** [comment]
Done https://github.com/LongRunning/LongRunning/releases/tag/0.2.0

**Pull request merged**
